### ISSUE TITLE
Legacy Grpc.Core fails on Linux Alpine container

### ISSUE THREAD

**Issue by baseTwo** [shubhamranjan/dotnet-etcd#109]
**Describe the bug**
The EtcdClient fails to connect on a Linux Alpine container running .net 5.

The underlying grpc library fails with the following error:

```
System.IO.IOException: Error loading native library "/app/runtimes/linux-x64/native/libgrpc_csharp_ext.x64.so". Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /app/runtimes/linux-x64/native/libgrpc_csharp_ext.x64.so)
   at Grpc.Core.Internal.UnmanagedLibrary..ctor(String[] libraryPathAlternatives)
   at Grpc.Core.Internal.NativeExtension.LoadNativeMethodsUsingExplicitLoad()
   at Grpc.Core.Internal.NativeExtension.LoadNativeMethods()
   at Grpc.Core.Internal.NativeExtension..ctor()
   at Grpc.Core.Internal.NativeExtension.Get()
   at Grpc.Core.Internal.NativeMethods.Get()
   at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
   at Grpc.Core.GrpcEnvironment..ctor()
   at Grpc.Core.GrpcEnvironment.AddRef()
   at Grpc.Core.Channel..ctor(String target, ChannelCredentials credentials, IEnumerable`1 options)
   at Grpc.Core.Channel..ctor(String host, Int32 port, ChannelCredentials credentials, IEnumerable`1 options)
   at dotnet_etcd.multiplexer.Balancer..ctor(List`1 nodes, String caCert, String clientCert, String clientKey, Boolean publicRootCa)
   at dotnet_etcd.EtcdClient..ctor(String connectionString, Int32 port, String caCert, String clientCert, String clientKey, Boolean publicRootCa)
```
Please note that Grpc.Net.Client is the recommended library for the future and that Grpc.Core will go into maintenance. This might be worth looking into as a solution for this bug.

https://grpc.io/blog/grpc-csharp-future/

**Comment by shubhamranjan** [comment]
Thanks for reporting. I will check it out and will plan out the switch to Grpc.Net.Client

**Comment by shubhamranjan** [comment]
I have tested and released a pre-release version. You may check it out.

Version: `5.0.0-alpha`

Thanks !

**Comment by baseTwo** [comment]
I am testing now using certificates, and getting the following exception when creating the EtcdClient whilst specifying the caCert, clientKey and clientCert parameters:

System.InvalidOperationException: SslCredentials with non-null arguments is not supported by GrpcChannel. GrpcChannel uses HttpClient to make gRPC calls and HttpClient automatically loads root certificates from the operating system certificate store. Client certificates should be configured on HttpClient. See https://aka.ms/aspnet/grpc/certauth for details.
   at Grpc.Net.Client.Internal.DefaultChannelCredentialsConfigurator.SetSslCredentials(Object state, String rootCertificates, KeyCertificatePair keyCertificatePair, VerifyPeerCallback verifyPeerCallback)
   at Grpc.Core.SslCredentials.InternalPopulateConfiguration(ChannelCredentialsConfiguratorBase configurator, Object state)
   at Grpc.Net.Client.GrpcChannel..ctor(Uri address, GrpcChannelOptions channelOptions)
   at Grpc.Net.Client.GrpcChannel.ForAddress(Uri address, GrpcChannelOptions channelOptions)
   at dotnet_etcd.multiplexer.Balancer..ctor(List`1 nodes, String caCert, String clientCert, String clientKey, Boolean publicRootCa)
   at dotnet_etcd.EtcdClient..ctor(String connectionString, Int32 port, String caCert, String clientCert, String clientKey, Boolean publicRootCa)
   ....

**Comment by shubhamranjan** [comment]
This seems a big change on how certs used to be loaded before. Have already pushed a few changes, should be able to test em and release a new version soon.

**Comment by baseTwo** [comment]
I managed to get a secure connection working by providing the new EtcdClient constructor with the HttpClientHandler containing  the certificates.

**Comment by shubhamranjan** [comment]
Thanks for the update. Will move release a stable version soon.
