### ISSUE TITLE
Run Lease on linux, System.MissingMethodException: Method not found: 'Google.Protobuf.FieldCodec...

### ISSUE THREAD

**Issue by spiderpoison** [shubhamranjan/dotnet-etcd#24]
My code like this:
```
            var leaseId = etcdClient.LeaseGrant(new LeaseGrantRequest
            {
                TTL = Info.alive_tick
            }).ID;

            etcdClient.Put(new PutRequest
            {
                Key = ByteString.CopyFromUtf8(key_alive),
                Value = ByteString.CopyFromUtf8(Info.ValueYes),
                Lease = leaseId
            });
```
When I run on mac, it is ok. 
But when I run on linux(centos 7), It throw Exception:
```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'Etcdserverpb.Lease' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Etcdserverpb.LeaseTimeToLiveResponse' threw an exception. ---> System.MissingMethodException: Method not found: 'Google.Protobuf.FieldCodec`1<Google.Protobuf.ByteString> Google.Protobuf.FieldCodec.ForBytes(UInt32)'.
   --- End of inner exception stack trace ---
   at Etcdserverpb.LeaseTimeToLiveResponse.get_Parser()
   at Etcdserverpb.Lease..cctor()
   --- End of inner exception stack trace ---
   at Etcdserverpb.Lease.LeaseClient.LeaseGrant(LeaseGrantRequest request, CallOptions options)
   at Etcdserverpb.Lease.LeaseClient.LeaseGrant(LeaseGrantRequest request, Metadata headers, Nullable`1 deadline, CancellationToken cancellationToken)
   at dotnet_etcd.EtcdClient.LeaseGrant(LeaseGrantRequest request)
   at battlecheck.core.etcd.BeDiscovery.Start() in /Users/zhangzhen/serverthreekingdom/src/vcs.taiyouxi.net/jws2/battlecheck/battlecheck/core/etcd/BeDiscovery.cs:line 48
   at battlecheck.Program.Main(String[] args) in /Users/zhangzhen/serverthreekingdom/src/vcs.taiyouxi.net/jws2/battlecheck/battlecheck/Program.cs:line 42
```

**Comment by shubhamranjan** [comment]
Can you confirm whether this behavior is for all method calls or only for `LeaseGrant` ?

**Comment by spiderpoison** [comment]
I tried "Put" and "Get" operations, it's ok.
```
            var url = new Uri("http://172.16.1.105:2379/");
            var etcdClient = new EtcdClient(url.Host, url.Port);
            etcdClient.Put("testa", "a");
            Console.WriteLine(etcdClient.GetVal("testa"));
```

**Comment by shubhamranjan** [comment]
Ok. This looks like an issue with `Google.Protobuf` which is not on the latest version currently on the published package. I have pushed the updated one to the master branch. I plan to release a new package this week. You can pull the master branch and test if the issue still persists.

**Comment by spiderpoison** [comment]
The master branch is ok. I had tested.
